/* tslint:disable */
/* eslint-disable */
/**
 * APIFlask
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setSearchParams, toPathString, createRequestFunction } from './common';
// @ts-ignore
import { BASE_PATH, BaseAPI } from './base';
export const EventSexEnum = {
    Male: 'male',
    Female: 'female',
    Both: 'both'
};
export const EventRelayEnum = {
    Relay: 'relay',
    Individual: 'individual'
};
export const EventUnitEnum = {
    Meters: 'meters',
    Yards: 'yards'
};
export const EventStrokeEnum = {
    Freestyle: 'freestyle',
    Backstroke: 'backstroke',
    Breaststroke: 'breaststroke',
    Butterfly: 'butterfly',
    Medley: 'medley'
};
/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration) {
    return {
        /**
         *
         * @summary Get Meet
         * @param {number} meetId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        meetMeetIdGet: async (meetId, options = {}) => {
            // verify required parameter 'meetId' is not null or undefined
            assertParamExists('meetMeetIdGet', 'meetId', meetId);
            const localVarPath = `/meet/{meet_id}`
                .replace(`{${"meet_id"}}`, encodeURIComponent(String(meetId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Home
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        rootGet: async (options = {}) => {
            const localVarPath = `/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        secretGet: async (options = {}) => {
            const localVarPath = `/secret`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
            const localVarHeaderParameter = {};
            const localVarQueryParameter = {};
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    };
};
/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function (configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration);
    return {
        /**
         *
         * @summary Get Meet
         * @param {number} meetId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async meetMeetIdGet(meetId, options) {
            const localVarAxiosArgs = await localVarAxiosParamCreator.meetMeetIdGet(meetId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         *
         * @summary Home
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async rootGet(options) {
            const localVarAxiosArgs = await localVarAxiosParamCreator.rootGet(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         *
         * @summary Data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async secretGet(options) {
            const localVarAxiosArgs = await localVarAxiosParamCreator.secretGet(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    };
};
/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration, basePath, axios) {
    const localVarFp = DefaultApiFp(configuration);
    return {
        /**
         *
         * @summary Get Meet
         * @param {number} meetId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        meetMeetIdGet(meetId, options) {
            return localVarFp.meetMeetIdGet(meetId, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Home
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        rootGet(options) {
            return localVarFp.rootGet(options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        secretGet(options) {
            return localVarFp.secretGet(options).then((request) => request(axios, basePath));
        },
    };
};
/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     *
     * @summary Get Meet
     * @param {number} meetId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    meetMeetIdGet(meetId, options) {
        return DefaultApiFp(this.configuration).meetMeetIdGet(meetId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     *
     * @summary Home
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    rootGet(options) {
        return DefaultApiFp(this.configuration).rootGet(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     *
     * @summary Data
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    secretGet(options) {
        return DefaultApiFp(this.configuration).secretGet(options).then((request) => request(this.axios, this.basePath));
    }
}
