SECURITY_REGISTERABLE = True
SECURITY_CHANGEABLE = True
SECURITY_RECOVERABLE = True
SECURITY_TWO_FACTOR = True
SECURITY_TWO_FACTOR_ENABLED_METHODS = ['authenticator']
SECURITY_TOTP_ISSUER = 'TEST TOTP'
SECURITY_OAUTH_ENABLE = True